#!/usr/bin/env python

from __future__ import print_function
import shutil,os,sys,subprocess,webbrowser,time
from os.path import expanduser
HOME=expanduser("~")
try:
    input = raw_input
except NameError:
    pass

ABS_FILE = os.path.abspath(__file__)
PATH_HERE=os.path.abspath(os.path.dirname(__file__))

LITLAB_ROOT=os.path.join(HOME,'litlab')
LITLAB_CORPUS_ROOT=os.path.join(LITLAB_ROOT,'corpora')
LITLAB_LLP_ROOT=os.path.join(LITLAB_ROOT,'llp')
LITLAB_SLINGSHOT_ROOT=os.path.join(LITLAB_ROOT,'slingshot')

GIT_PATH_ID_RSA = os.path.join(HOME,'.ssh','id_rsa')


URL_LITLAB_GIT='git@github.com:quadrismegistus/litlab.git'
URL_LLP_GIT='git@github.com:quadrismegistus/llp.git'
URL_SLINGSHOT_GIT='git@github.com:quadrismegistus/mpi-slingshot.git'
URL_BOGUSTEST_GIT='git@github.com:erikfredner/test.git'


PIP_PACKAGES=sorted(
	['bs4','xopen','bleach','ujson','unicodecsv','mpi4py','numpy','pandas','scipy','paramiko',
	'spacy','stanfordnlp','nltk','paramiko','smart_open','wget']
)

PATH_BASH_PROFILE = os.path.join(HOME,'.bash_profile')


	 #,'scikit-learn']
#BREW_CASK_CMD='ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" < /dev/null 2> /dev/null ; brew install caskroom/cask/brew-cask 2> /dev/null'



GITHUB_USERNAME=''
GITHUB_EMAIL=''

NAP=5

def which(cmd):
	try:
		output = subprocess.check_output('source $HOME/.bash_profile; which '+cmd, shell=True) #, stderr=subprocess.STDOUT)
		return str(output)
	except Exception:
		return None

def print_logo():
	with open(os.path.join(PATH_HERE,'logo.txt')) as f:
		logo=f.read()

	print(logo)



def source_bash_profile():
	if os.path.exists(PATH_BASH_PROFILE) and which('source'):
		execute('source '+PATH_BASH_PROFILE)

def execute(cmd):
	print('>> executing:',cmd)
	os.system(cmd)
	#output = subprocess.check_output(cmd.split())
	#return output

def hidden_execute(cmd):
	output=''
	try:
		#output=subprocess.check_output(cmd.split())
		result = subprocess.run(cmd.split(), stdout=subprocess.PIPE)
		output = result.stdout
	except subprocess.CalledProcessError as e:
		print(e.output)
	return str(output)

def test_if_exec_exists(exec_name):
	return bool(which(exec_name))


## STEP 1. Check Brew


def check_brew():
	cmd_install_brew='/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"'

	print('>> Checking whether HomeBrew is installed...')
	brew_path = which('brew')
	if not brew_path:
		print('\n!! Homebrew not installed!')
		answer = input('\n?? Would you like to install homebrew? [Y/n]\n')
		if answer.strip().lower()!='n':
			execute(cmd_install_brew)
			return check_brew()
		else:
			print('>> Please install Homebrew on your own: https://brew.sh/')
			return False

	return True






## Step 2. Check Anaconda


import os,sys
def check_anaconda():
	print('>> Checking whether Anaconda (for Python 3.x) is installed...')
	anaconda_path = which('conda')
	pip_path = which('pip')
	python_path = which('python')
	if not anaconda_path or not 'anaconda3' in anaconda_path or not 'anaconda3' in pip_path:
		print('\n!! Anaconda3 not installed!')
		answer = input('\n?? Would you like to install Anaconda3? [Y/n]\n')
		if answer.strip().lower()!='n':
			#execute('brew cask install anaconda')
			os.system('curl -o $HOME/anaconda3.sh https://repo.continuum.io/archive/Anaconda3-2019.07-MacOSX-x86_64.sh')
			os.system('bash ~/anaconda3.sh -b -p $HOME/anaconda3')
			os.system('echo "export PATH=\"$HOME/anaconda3/bin:$PATH\"\n" >> $HOME/.bash_profile')
			os.system('source $HOME/.bash_profile')
			#os.execl('$HOME/anaconda3/bin/python',*sys.argv)
			#return check_anaconda()
			reboot_with_anaconda()
		else:
			print('>> Please install Anaconda for Python 3.x on your own: https://www.anaconda.com/distribution/')
			return False

	else:
		if 'anaconda3' not in sys.executable:
			reboot_with_anaconda()
			#os.execl('%s/anaconda3/bin/python' % os.path.expanduser('~'),'python',__file__)
		return True

def reboot_with_anaconda():
	import time
	print('\n >> Rebooting this script using the anaconda3 version of python . . .\n')
	time.sleep(1)
	os.execl('%s/anaconda3/bin/python' % os.path.expanduser('~'),'python',ABS_FILE)

# def add_anaconda_to_path():
# 	anaconda_path = which('conda')
# 	anaconda_bin_path = os.path.split(anaconda_path)[0]
#
# 	ofn=os.path.join(HOME,'.bash_profile')
# 	with open(ofn,'a+') as of:
# 		print('\n\nexport PATH=%s:$PATH' % anaconda_bin_path)
#




## Step 3. Check pip packages

def is_package_installed(pkgname):
	import subprocess
	FNULL = open(os.devnull, 'w')
	try:
		subprocess.check_output('$HOME/anaconda3/bin/python -c "import %s" >> /dev/null' % pkgname,shell=True)
		return True
	except subprocess.CalledProcessError:
		return False


def check_packages():
	#import importlib.util

	print('>> Installing common Python packages...')

	#need_reboot=False
	for pkg in PIP_PACKAGES:
		#spec = importlib.util.find_spec(pkg)
		#if spec is None:
		if not is_package_installed(pkg):
			print('>>',pkg +" is not installed...")
			cmd='$HOME/anaconda3/bin/pip install %s' % pkg
			print('>> executing:',cmd)
			os.system(cmd)

	#if need_reboot:
	#	import os,sys
	#	os.execl('$HOME/anaconda3/bin/python',)
	return True





def check_apps():
	print('>> Checking whether basic Mac apps are installed...')
	#for cmd in BREW_INSTALL_CMDS:
	#	execute(cmd)

	#if not os.path.exists('/Applications/TextMate.app'):
	#	print('>> Installing TextMate, a good and open-source text editor for Mac...')
	#	execute('brew cask install textmate')

	if not os.path.exists('/Applications/Atom.app'):
		print('>> Installing Atom, a good and open-source text editor for Mac...')
		execute('brew cask install atom')

	#if not os.path.exists('/Applications/iTerm.app'):
	#	print('>> Installing iTerm2, a good and open-source terminal for Mac...')
	#	execute('brew cask install iterm2')

	#if not test_if_exec_exists('wget'):
	#	print('>> Installing wget, which lets us download things from the Terminal...')
	#	execute('brew install wget')

	if not test_if_exec_exists('git'):
		print('>> Installing git, which lets us use github to download/upload code collaboratively...')
		execute('brew install git')

	return True


## GIT

def check_ssh():
	import paramiko
	ssh = paramiko.SSHClient()
	ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
	from paramiko.ssh_exception import SSHException,BadHostKeyException,AuthenticationException,socket

	try:
		#ssh.connect('github.com', username='git', key_filename=key_file)
		ssh.connect('github.com', username='git')
		print('>> Successfully connected to Github\'s SSH server!')
		return True
	except (BadHostKeyException, AuthenticationException, SSHException, socket.error) as e:
		print(e)
		#sleep(interval)
		return False

def get_git_user_info():
	global GITHUB_USERNAME,GITHUB_EMAIL

	if not GITHUB_USERNAME: GITHUB_USERNAME = input('\n>> What is your github username? (If you do not have one, please register now @ https://github.com)\n')
	if not GITHUB_EMAIL: GITHUB_EMAIL = input('\n>> What is your github email address?\n')

def ssh_key_exists(path_id_rsa):
	path_id_rsa = os.path.join(HOME,'id_rsa') if not path_id_rsa else path_id_rsa
	path_id_rsa_pub = path_id_rsa+'.pub'
	return os.path.exists(path_id_rsa) and os.path.exists(path_id_rsa_pub)

def git_gen_ssh_key(path_id_rsa):
	global GITHUB_USERNAME,GITHUB_EMAIL

	if ssh_key_exists(path_id_rsa) and False:
		print('>> SSH keys already exist')
	else:
		print('>> No SSH keys exist already')

		get_git_user_info()

		if not GITHUB_EMAIL or not GITHUB_USERNAME:
			print('>> Please re-run this installer once you have a github account')
			exit()

		cmd='ssh-keygen -q -N "" -f {path} -t rsa -b 4096 -C "{email}"'.format(path=path_id_rsa, email=GITHUB_EMAIL)
		execute(cmd)

		if not ssh_key_exists(path_id_rsa):
		#if True:
			url='https://help.github.com/en/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent'
			print('>> SSH Keygen creation failed. Please follow these instructions manually:',url)
			time.sleep(2)
			webbrowser.open_new(url)
			exit()

def git_add_ssh_key_to_agent(path_id_rsa):
	# start up agent
	execute('eval "$(ssh-agent -s)"')

	# add opt to ssh config
	ssh_config_path=os.path.join(HOME,'.ssh','config')
	with open(ssh_config_path,'a+') as of:
		of.write('Host *\n\tAddKeysToAgent yes\n\tUseKeychain yes\n\tIdentityFile {path}\n\n'.format(path=path_id_rsa))

	execute('ssh-add -K '+path_id_rsa)

def git_add_ssh_key_to_github(path_id_rsa):
	execute('pbcopy < '+path_id_rsa+'.pub')

	url='https://github.com/settings/ssh/new'

	print('\n#### MANUAL STEP NECESSARY ####')
	print('>> Your SSH Key has been copied to your clipboard.')
	print(' - Please paste it in the "Key" box on this page: '+url)
	print(' - Any Title is fine. The name of your computer is your recommended')
	print(' - Loading the above URL automatically in %s seconds...' % NAP)
	print(' - Once you\'re done, press any key to continue')
	time.sleep(NAP)
	webbrowser.open_new(url)
	x=input()
	print ('>> Continuing...')


def check_git(path_id_rsa=GIT_PATH_ID_RSA):
	global GITHUB_USERNAME,GITHUB_EMAIL

	#print('>> using key:',path_id_rsa)

	print('>> Checking whether git is set up to connect to GitHub using SSH...')
	ssh_ok = check_ssh()
	if ssh_ok: return True

	# Step 0. Make sure SSH directory exists
	path_dot_ssh=os.path.join(HOME,'.ssh')
	if not os.path.exists(path_dot_ssh): os.mkdir(path_dot_ssh)

	# Step 1. Make Key

	#print('>> using key:',path_id_rsa)
	git_gen_ssh_key(path_id_rsa)

	# Step 2. Add key to key list
	git_add_ssh_key_to_agent(path_id_rsa)

	# Step 3.
	git_add_ssh_key_to_github(path_id_rsa)

	# Test whether ok
	ssh_ok = check_ssh()
	if not ssh_ok:
		url='https://help.github.com/en/articles/connecting-to-github-with-ssh'
		print('\n>> Still cannot connect to Github SSH. Please follow these instructions manually:\n'+url)
		time.sleep(NAP)
		webbrowser.open_new(url)
		exit()

	reboot_with_anaconda()




### STEP 6. Installing Lab Software

def clone_repo(path_to_cd_to, repo_name, git_url, final_path=None):
	path_of_cloned_dir = os.path.join(path_to_cd_to,repo_name)
	os.chdir(path_to_cd_to)
	try:
		out=execute('git clone {git_url} && cd {repo_name} && git submodule init && git submodule update'.format(git_url=git_url,repo_name=repo_name))
		if final_path: os.rename(path_of_cloned_dir,final_path)

	except subprocess.CalledProcessError as e:

		print(e)

		print('\n!! ERROR: You do not yet have access to the private Literary Lab repositories.')
		print('!! Please email Ryan Heuser (heuser@stanford.edu) with your github username to gain access.')

		exit()


def check_lab_software():
	# LLP
	llp_path_to_cd_to = os.path.abspath(os.path.join(LITLAB_LLP_ROOT,'..'))
	add_to_python_path(llp_path_to_cd_to)
	add_to_python_path(LITLAB_SLINGSHOT_ROOT)
	add_to_path( os.path.join(LITLAB_LLP_ROOT,'bin') )
	add_to_path( os.path.join(LITLAB_SLINGSHOT_ROOT,'bin') )


	execute('source ~/.bash_profile')


	if not os.path.exists(LITLAB_ROOT):
		path_to_cd_to=os.path.abspath(os.path.join(LITLAB_ROOT,'..'))
		clone_repo(path_to_cd_to, 'litlab', URL_LITLAB_GIT)
		reboot_with_anaconda()
	else:
		print('>> updating existing repository:',LITLAB_ROOT)
		os.chdir(LITLAB_ROOT)
		execute('git pull')
		execute('git submodule update')


	return True




def add_to_path(path, path_bash_profile=PATH_BASH_PROFILE,pathtype='PATH'):
	if os.path.exists(path_bash_profile):
		with open(path_bash_profile) as f:
			for ln in f:
				if ('$'+pathtype in ln) and path in ln: # (path in ln.replace('=',' ').replace(':',' ').split()):
					# already done
					#print('!',ln)
					return True

	# not found? ok then write it
	with open(path_bash_profile,'a+') as of:
		newln='export {pathtype}="{newpath}:${pathtype}"      #from litlab-starterpack\n'.format(pathtype=pathtype,newpath=path)
		of.write(newln)
		#print(newln)

def add_to_python_path(path, path_bash_profile=PATH_BASH_PROFILE):
	if not path in sys.path: sys.path.insert(0,path)
	return add_to_path(path, path_bash_profile=path_bash_profile, pathtype='PYTHONPATH')


def install_basic_llp(corpora=['MarkMark']):
	print('>> checking for corpora through LLP')
	import llp
	print(llp.__file__)
	for cname in corpora:
		corpus = llp.load(cname)
		if not os.path.exists(corpus.path_metadata):
			print('>> downloading corpus:',cname)
			corpus.download()
	return True




## MAIN

def run_all():
	# Source the profile
	source_bash_profile()

	# Set the steps
	steps = [
		check_brew,  			# 1
		check_anaconda, 		# 2
		check_packages,			# 3
		check_apps,				# 4
		check_git,				# 5
		check_lab_software,		# 6
		install_basic_llp]		# 7
	#steps = []
	num_steps = len(steps)

	# Run through the steps
	for i,step in enumerate(steps):
		print('\n>> Step #%s of %s' % (i+1, num_steps))
		res=step()
		if res is not True:
			exit()
		else:
			print('>> Success!')

if __name__=='__main__':
	print_logo()
	print('>> Welcome to the Literary Lab Starter Pack Installer!')
	time.sleep(2)

	run_all()

	print('\n>> All set up! Happy hacking...')
