#!/usr/bin/env python

from __future__ import print_function
import shutil,os,sys,subprocess,webbrowser,time
from os.path import expanduser
HOME=expanduser("~")

PATH_HERE=os.path.abspath(os.path.dirname(__file__))

LITLAB_ROOT=os.path.join(HOME,'litlab')
LITLAB_CORPUS_ROOT=os.path.join(LITLAB_ROOT,'corpora')
LITLAB_LLP_ROOT=os.path.join(LITLAB_ROOT,'llp')
LITLAB_SLINGSHOT_ROOT=os.path.join(LITLAB_ROOT,'slingshot')

GIT_PATH_ID_RSA = os.path.join(HOME,'.ssh','id_rsa')


URL_LLP_GIT='git@github.com:quadrismegistus/llp_lab.git'
URL_SLINGSHOT_GIT='git@github.com:quadrismegistus/mpi-slingshot.git'
URL_BOGUSTEST_GIT='git@github.com:erikfredner/test.git'


PIP_PACKAGES=sorted(
	['bs4','xopen','bleach','ujson','unicodecsv','mpi4py','numpy','pandas','scipy','paramiko',
	'spacy','nltk']
)

PATH_BASH_PROFILE = os.path.join(HOME,'.bash_profile')


	 #,'scikit-learn']
#BREW_CASK_CMD='ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" < /dev/null 2> /dev/null ; brew install caskroom/cask/brew-cask 2> /dev/null'



GITHUB_USERNAME=''
GITHUB_EMAIL=''

NAP=5


"""
BREW_INSTALL_CMDS = [
	#BREW_CASK_CMD,
	'brew install wget',
	'brew cask install iterm2',
	'brew cask install textmate'
]
"""

def source_bash_profile():
	if os.path.exists(PATH_BASH_PROFILE) and shutil.which('source'):
		exec('source '+PATH_BASH_PROFILE)

def exec(cmd):
	print('>> executing:',cmd)
	os.system(cmd)
	#output = subprocess.check_output(cmd.split())
	#return output

def hidden_exec(cmd):
	output=''
	try:
		#output=subprocess.check_output(cmd.split())
		result = subprocess.run(cmd.split(), stdout=subprocess.PIPE)
		output = result.stdout
	except subprocess.CalledProcessError as e:
		print(e.output)
	return str(output)

def test_if_exec_exists(exec_name):
	return bool(shutil.which(exec_name))


## STEP 1. Check Brew


def check_brew():
	cmd_install_brew='/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"'

	print('>> Checking whether HomeBrew is installed...')
	brew_path = shutil.which('brew')
	if not brew_path:
		print('\n!! Homebrew not installed!')
		answer = input('\n?? Would you like to install homebrew? [Y/n]\n')
		if answer.strip().lower()!='n':
			exec(cmd_install_brew)
			return check_brew()
		else:
			print('>> Please install Homebrew on your own: https://brew.sh/')
			return False

	return True






## Step 2. Check Anaconda



def check_anaconda():
	print('>> Checking whether Anaconda (for Python 3.x) is installed...')
	anaconda_path = shutil.which('conda')
	pip_path = shutil.which('pip')
	python_path = shutil.which('python')
	if not anaconda_path or not 'anaconda3' in anaconda_path or not 'anaconda3' in pip_path:
		print('\n!! Anaconda3 not installed!')
		answer = input('\n?? Would you like to install Anaconda3? [Y/n]\n')
		if answer.strip().lower()!='n':
			exec('brew cask install anaconda')
			return check_anaconda()
		else:
			print('>> Please install Anaconda for Python 3.x on your own: https://www.anaconda.com/distribution/')
			return False

	else:
		return True

# def add_anaconda_to_path():
# 	anaconda_path = shutil.which('conda')
# 	anaconda_bin_path = os.path.split(anaconda_path)[0]
#
# 	ofn=os.path.join(HOME,'.bash_profile')
# 	with open(ofn,'a+') as of:
# 		print('\n\nexport PATH=%s:$PATH' % anaconda_bin_path)
#




## Step 3. Check pip packages


def check_packages():
	import importlib.util

	print('>> Installing common Python packages...')

	for pkg in PIP_PACKAGES:
		spec = importlib.util.find_spec(pkg)
		if spec is None:
			print('>>',pkg +" is not installed...")
			cmd='pip install %s' % pkg
			print('>> executing:',cmd)
			os.system(cmd)

	return True





def check_apps():
	print('>> Checking whether basic Mac apps are installed...')
	#for cmd in BREW_INSTALL_CMDS:
	#	exec(cmd)

	if not os.path.exists('/Applications/TextMate.app'):
		print('>> Installing TextMate, a good and open-source text editor for Mac...')
		exec('brew cask install textmate')

	if not os.path.exists('/Applications/iTerm.app'):
		print('>> Installing iTerm2, a good and open-source terminal for Mac...')
		exec('brew cask install iterm2')

	if not test_if_exec_exists('wget'):
		print('>> Installing wget, which lets us download things from the Terminal...')
		exec('brew install wget')

	if not test_if_exec_exists('git'):
		print('>> Installing git, which lets us use github to download/upload code collaboratively...')
		exec('brew install git')

	return True


## GIT

def check_ssh():
	import paramiko
	ssh = paramiko.SSHClient()
	ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
	from paramiko.ssh_exception import SSHException,BadHostKeyException,AuthenticationException,socket

	try:
		#ssh.connect('github.com', username='git', key_filename=key_file)
		ssh.connect('github.com', username='git')
		print('>> Successfully connected to Github\'s SSH server!')
		return True
	except (BadHostKeyException, AuthenticationException, SSHException, socket.error) as e:
		print(e)
		#sleep(interval)
		return False

def get_git_user_info():
	global GITHUB_USERNAME,GITHUB_EMAIL

	if not GITHUB_USERNAME: GITHUB_USERNAME = input('\n>> What is your github username? (If you do not have one, please register now @ https://github.com)\n')
	if not GITHUB_EMAIL: GITHUB_EMAIL = input('\n>> What is your github email address?\n')

def ssh_key_exists(path_id_rsa):
	path_id_rsa = os.path.join(HOME,'id_rsa') if not path_id_rsa else path_id_rsa
	path_id_rsa_pub = path_id_rsa+'.pub'
	return os.path.exists(path_id_rsa) and os.path.exists(path_id_rsa_pub)

def git_gen_ssh_key(path_id_rsa):
	global GITHUB_USERNAME,GITHUB_EMAIL

	if ssh_key_exists(path_id_rsa) and False:
		print('>> SSH keys already exist')
	else:
		print('>> No SSH keys exist already')

		get_git_user_info()

		if not GITHUB_EMAIL or not GITHUB_USERNAME:
			print('>> Please re-run this installer once you have a github account')
			exit()

		cmd='ssh-keygen -q -N "" -f {path} -t rsa -b 4096 -C "{email}"'.format(path=path_id_rsa, email=GITHUB_EMAIL)
		exec(cmd)

		if not ssh_key_exists(path_id_rsa):
		#if True:
			url='https://help.github.com/en/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent'
			print('>> SSH Keygen creation failed. Please follow these instructions manually:',url)
			time.sleep(2)
			webbrowser.open_new(url)
			exit()

def git_add_ssh_key_to_agent(path_id_rsa):
	# start up agent
	exec('eval "$(ssh-agent -s)"')

	# add opt to ssh config
	ssh_config_path=os.path.join(HOME,'.ssh','config')
	with open(ssh_config_path,'a+') as of:
		of.write('Host *\n\tAddKeysToAgent yes\n\tUseKeychain yes\n\tIdentityFile {path}\n\n'.format(path=path_id_rsa))

	exec('ssh-add -K '+path_id_rsa)

def git_add_ssh_key_to_github(path_id_rsa):
	exec('pbcopy < '+path_id_rsa+'.pub')

	url='https://github.com/settings/ssh/new'

	print('\n#### MANUAL STEP NECESSARY ####')
	print('>> Your SSH Key has been copied to your clipboard.')
	print(' - Please paste it in the "Key" box on this page: '+url)
	print(' - Any Title is fine. The name of your computer is your recommended')
	print(' - Loading the above URL automatically in %s seconds...' % NAP)
	print(' - Once you\'re done, press any key to continue')
	time.sleep(NAP)
	webbrowser.open_new(url)
	x=input()
	print ('>> Continuing...')


def check_git(path_id_rsa=GIT_PATH_ID_RSA):
	global GITHUB_USERNAME,GITHUB_EMAIL

	#print('>> using key:',path_id_rsa)

	print('>> Checking whether git is set up to connect to GitHub using SSH...')
	ssh_ok = check_ssh()
	if ssh_ok: return True

	# Step 0. Make sure SSH directory exists
	path_dot_ssh=os.path.join(HOME,'.ssh')
	if not os.path.exists(path_dot_ssh): os.mkdir(path_dot_ssh)

	# Step 1. Make Key

	#print('>> using key:',path_id_rsa)
	git_gen_ssh_key(path_id_rsa)

	# Step 2. Add key to key list
	git_add_ssh_key_to_agent(path_id_rsa)

	# Step 3.
	git_add_ssh_key_to_github(path_id_rsa)

	# Test whether ok
	ssh_ok = check_ssh()
	if not ssh_ok:
		url='https://help.github.com/en/articles/connecting-to-github-with-ssh'
		print('\n>> Still cannot connect to Github SSH. Please follow these instructions manually:\n'+url)
		time.sleep(NAP)
		webbrowser.open_new(url)
		exit()




### STEP 6. Installing Lab Software

def clone_repo(path_to_cd_to, repo_name, git_url, final_path):
	path_of_cloned_dir = os.path.join(path_to_cd_to,repo_name)
	os.chdir(path_to_cd_to)
	try:
		out=exec('git clone {git_url}'.format(git_url=git_url))
		os.rename(path_of_cloned_dir,final_path)

	except subprocess.CalledProcessError as e:

		print(e)

		print('\n!! ERROR: You do not yet have access to the private Literary Lab repositories.')
		print('!! Please email Ryan Heuser (heuser@stanford.edu) with your github username to gain access.')

		exit()


def check_lab_software():
	# make sure litlab and corpus folders are installed
	for path in [LITLAB_ROOT,LITLAB_CORPUS_ROOT]:
		if not os.path.exists(path):
			os.makedirs(path)

	# LLP
	llp_path_to_cd_to = os.path.abspath(os.path.join(LITLAB_LLP_ROOT,'..'))
	add_to_python_path(llp_path_to_cd_to)
	if not os.path.exists(LITLAB_LLP_ROOT):
		path_to_cd_to=llp_path_to_cd_to
		path_of_cloned_dir = os.path.join(path_to_cd_to,'llp_lab')
		path_final=LITLAB_LLP_ROOT
		url_git=URL_LLP_GIT

		if not os.path.exists(path_of_cloned_dir):
			clone_repo(path_to_cd_to, path_of_cloned_dir, url_git, path_final)
		elif not os.path.exists(LITLAB_LLP_ROOT):
			os.rename(path_of_cloned_dir, path_final)
		else:
			pass  # ?

	else:
		print('>> updating existing repository:',LITLAB_LLP_ROOT)
		os.chdir(LITLAB_LLP_ROOT)
		exec('git pull')

	# Slingshot
	if not os.path.exists(LITLAB_SLINGSHOT_ROOT):
		path_to_cd_to = os.path.abspath(os.path.join(LITLAB_SLINGSHOT_ROOT,'..'))
		path_of_cloned_dir = os.path.join(path_to_cd_to,'mpi-slingshot')
		path_final=LITLAB_SLINGSHOT_ROOT
		url_git=URL_SLINGSHOT_GIT

		if not os.path.exists(path_of_cloned_dir):
			clone_repo(path_to_cd_to, path_of_cloned_dir, url_git, path_final)
		elif not os.path.exists(LITLAB_LLP_ROOT):
			os.rename(path_of_cloned_dir, path_final)
		else:
			pass  # ?
	else:
		print('>> updating existing repository:',LITLAB_SLINGSHOT_ROOT)
		os.chdir(LITLAB_SLINGSHOT_ROOT)
		exec('git pull')
	# no matter what?

	add_to_python_path(LITLAB_SLINGSHOT_ROOT)
	add_to_path( os.path.join(LITLAB_SLINGSHOT_ROOT,'bin') )


	## make sure llp_config.txt is saved
	lab_llp_config_path = os.path.join(LITLAB_ROOT,'llp_config.txt')
	lab_llp_manifest_path = os.path.join(LITLAB_ROOT,'llp_manifest.txt')

	if not os.path.exists(lab_llp_config_path):
		#shutil.copyfile(PATH_HERE)
		lab_path_config_default=os.path.join(PATH_HERE,'llp_config.txt')
		#print(lab_path_config_default, lab_llp_config_path)
		shutil.copyfile(lab_path_config_default, lab_llp_config_path)

	return True


	#cmd='git clone {git_url}'.format(path=LITLAB_ROOT, git_url=URL_BOGUSTEST_GIT)
	#out=exec(cmd)

	#clone_repo(LITLAB_ROOT, 'test', URL_BOGUSTEST_GIT, '/Users/ryan/litlab/test')

def add_to_path(path, path_bash_profile=PATH_BASH_PROFILE,pathtype='PATH'):
	if os.path.exists(path_bash_profile):
		with open(path_bash_profile) as f:
			for ln in f:
				if ('$'+pathtype in ln) and (path in ln.replace('=',' ').replace(':',' ').split()):
					# already done
					print('!',ln)
					return True

	# not found? ok then write it
	with open(path_bash_profile,'a+') as of:
		newln='\n\nexport {pathtype}="{newpath}:${pathtype}"      #from litlab-starterpack\n\n'.format(pathtype=pathtype,newpath=path)
		of.write(newln)
		#print(newln)

def add_to_python_path(path, path_bash_profile=PATH_BASH_PROFILE):
	return add_to_path(path, path_bash_profile=path_bash_profile, pathtype='PYTHONPATH')


def install_basic_llp(corpora=['MarkMark']):
	import llp
	for cname in corpora:
		corpus = llp.load(cname)
		if not os.path.exists(corpus.path_metadata):
			corpus.download()
	return True




## MAIN

def run_all():
	# Source the profile
	source_bash_profile()

	# Set the steps
	steps = [check_brew, check_anaconda, check_packages, check_apps, check_git, check_lab_software, install_basic_llp]
	#steps = []
	num_steps = len(steps)

	# Run through the steps
	for i,step in enumerate(steps):
		print('\n>> Step #%s of %s' % (i+1, num_steps))
		res=step()
		if res is not True:
			exit()
		else:
			print('>> Success!')

if __name__=='__main__':
	print('>> Welcome to the Literary Lab Starter Pack Installer!')

	run_all()

	print('\n>> All set up! Happy hacking...')
